import featurecard1 from  '../assets/featurecard1.avif';
import {AiOutlineHeart} from 'react-icons/ai';
import {MdBedroomChild} from 'react-icons/md';
import {MdBathroom} from 'react-icons/md';
import {BiArea} from 'react-icons/bi';
export const cardsdata = [
    {
      id:1,
      src:featurecard1,
      category:"Home",
      alt:"featurecard",
      icon:<AiOutlineHeart/>,
      iconbed:<MdBedroomChild/>,
      iconbath:<MdBathroom/>,
      iconarea:<BiArea/>,
      heading:"Home In Merrick Way",
      description:"Enchanting three bedrooms, three bath home with spacious one bedroom, one bath...",
      bedroom:"Bedrooms",
      bathroom:"Bathrooms",
      area:"Area",
      Nofobedroom:3,
      Nofobathroom:3,
      NofoArea:4300,
      NofoAreaft: "Sq Ft",
      sale:"For Sale",
      price:"$540,000"
   
    },
    {
      id:2,
      src:featurecard1,
      category:"Home",
      alt:"featurecard",
      icon:<AiOutlineHeart/>,
      iconbed:<MdBedroomChild/>,
      iconbath:<MdBathroom/>,
      iconarea:<BiArea/>,
      heading:"Home In Merrick Way",
      description:"Enchanting three bedrooms, three bath home with spacious one bedroom, one bath...",
      bedroom:"Bedrooms",
      bathroom:"Bathrooms",
      area:"Area",
      Nofobedroom:3,
      Nofobathroom:3,
      NofoArea:4300,
      NofoAreaft: "Sq Ft",
      sale:"For Sale",
      price:"$540,000"
   
    },
    {
      id:3,
      src:featurecard1,
      category:"OFFICE",
      alt:"featurecard",
      icon:<AiOutlineHeart/>,
      iconbed:<MdBedroomChild/>,
      iconbath:<MdBathroom/>,
      iconarea:<BiArea/>,
      heading:"Home In Merrick Way",
      description:"Enchanting three bedrooms, three bath home with spacious one bedroom, one bath...",
      bedroom:"Bedrooms",
      bathroom:"Bathrooms",
      area:"Area",
      Nofobedroom:3,
      Nofobathroom:3,
      NofoArea:4300,
      NofoAreaft: "Sq Ft",
      sale:"For Sale",
      price:"$540,000"
   
    },
    {
      id:4,
      src:featurecard1,
      category:"OFFICE",
      alt:"featurecard",
      icon:<AiOutlineHeart/>,
      iconbed:<MdBedroomChild/>,
      iconbath:<MdBathroom/>,
      iconarea:<BiArea/>,
      heading:"Home In Merrick Way",
      description:"Enchanting three bedrooms, three bath home with spacious one bedroom, one bath...",
      bedroom:"Bedrooms",
      bathroom:"Bathrooms",
      area:"Area",
      Nofobedroom:3,
      Nofobathroom:3,
      NofoArea:4300,
      NofoAreaft: "Sq Ft",
      sale:"For Sale",
      price:"$540,000"
   
    },
    {
      id:5,
      src:featurecard1,
      category:"APARTMENT",
      alt:"featurecard",
      icon:<AiOutlineHeart/>,
      iconbed:<MdBedroomChild/>,
      iconbath:<MdBathroom/>,
      iconarea:<BiArea/>,
      heading:"Home In Merrick Way",
      description:"Enchanting three bedrooms, three bath home with spacious one bedroom, one bath...",
      bedroom:"Bedrooms",
      bathroom:"Bathrooms",
      area:"Area",
      Nofobedroom:3,
      Nofobathroom:3,
      NofoArea:4300,
      NofoAreaft: "Sq Ft",
      sale:"For Sale",
      price:"$540,000"
   
    },
    {
      id:6,
      src:featurecard1,
      category:"APARTMENT",
      alt:"featurecard",
      icon:<AiOutlineHeart/>,
      iconbed:<MdBedroomChild/>,
      iconbath:<MdBathroom/>,
      iconarea:<BiArea/>,
      heading:"Home In Merrick Way",
      description:"Enchanting three bedrooms, three bath home with spacious one bedroom, one bath...",
      bedroom:"Bedrooms",
      bathroom:"Bathrooms",
      area:"Area",
      Nofobedroom:3,
      Nofobathroom:3,
      NofoArea:4300,
      NofoAreaft: "Sq Ft",
      sale:"For Sale",
      price:"$540,000"
   
    }
] 